name: manage-azure-policy-35f4cc03
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Log_Analytics_agent_should_be_installed_on_your_Cloud_Services_(extended_support)_role_instances_15fdbc87-8a47-4ee9-a2aa-9a2ea1f37554/**'
#      - .github/workflows/manage-azure-policy-35f4cc03.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_35f4cc03}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Log_Analytics_agent_should_be_installed_on_your_Cloud_Services_(extended_support)_role_instances_15fdbc87-8a47-4ee9-a2aa-9a2ea1f37554/**
