name: manage-azure-policy-b523eff1
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/SQL_Server_should_use_a_virtual_network_service_endpoint_ae5d2f14-d830-42b6-9899-df6cfe9c71a3/**'
#      - .github/workflows/manage-azure-policy-b523eff1.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_b523eff1}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/SQL_Server_should_use_a_virtual_network_service_endpoint_ae5d2f14-d830-42b6-9899-df6cfe9c71a3/**
