name: manage-azure-policy-e2f830c9
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_Monitor_Private_Link_Scope_should_block_access_to_non_private_link_resources_a499fed8-bcc8-4195-b154-641f14743757/**'
#      - .github/workflows/manage-azure-policy-e2f830c9.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_e2f830c9}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_Monitor_Private_Link_Scope_should_block_access_to_non_private_link_resources_a499fed8-bcc8-4195-b154-641f14743757/**
