name: manage-azure-policy-46291c16
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Event_Hub_namespaces_should_use_private_link_b8564268-eb4a-4337-89be-a19db070c59d/**'
#      - .github/workflows/manage-azure-policy-46291c16.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_46291c16}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Event_Hub_namespaces_should_use_private_link_b8564268-eb4a-4337-89be-a19db070c59d/**
