name: manage-azure-policy-3a5628a0
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Internet-facing_virtual_machines_should_be_protected_with_network_security_groups_f6de0be7-9a8a-4b8a-b349-43cf02d22f7c/**'
#      - .github/workflows/manage-azure-policy-3a5628a0.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_3a5628a0}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Internet-facing_virtual_machines_should_be_protected_with_network_security_groups_f6de0be7-9a8a-4b8a-b349-43cf02d22f7c/**
