name: manage-azure-policy-d23a4f6f
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/An_activity_log_alert_should_exist_for_specific_Security_operations_3b980d31-7904-4bb7-8575-5665739a8052/**'
#      - .github/workflows/manage-azure-policy-d23a4f6f.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_d23a4f6f}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/An_activity_log_alert_should_exist_for_specific_Security_operations_3b980d31-7904-4bb7-8575-5665739a8052/**
