name: manage-azure-policy-bcc8fa66
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/IP_Forwarding_on_your_virtual_machine_should_be_disabled_bd352bd5-2853-4985-bf0d-73806b4a5744/**'
#      - .github/workflows/manage-azure-policy-bcc8fa66.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_bcc8fa66}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/IP_Forwarding_on_your_virtual_machine_should_be_disabled_bd352bd5-2853-4985-bf0d-73806b4a5744/**
