name: manage-azure-policy-f2a8975b
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Log_Analytics_agent_should_be_installed_on_your_virtual_machine_scale_sets_for_Azure_Security_Center_monitoring_a3a6ea0c-e018-4933-9ef0-5aaa1501449b/**'
#      - .github/workflows/manage-azure-policy-f2a8975b.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_f2a8975b}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Log_Analytics_agent_should_be_installed_on_your_virtual_machine_scale_sets_for_Azure_Security_Center_monitoring_a3a6ea0c-e018-4933-9ef0-5aaa1501449b/**
