name: manage-azure-policy-96f8679f
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Log_connections_should_be_enabled_for_PostgreSQL_database_servers_eb6f77b9-bd53-4e35-a23d-7f65d5f0e442/**'
#      - .github/workflows/manage-azure-policy-96f8679f.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_96f8679f}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Log_connections_should_be_enabled_for_PostgreSQL_database_servers_eb6f77b9-bd53-4e35-a23d-7f65d5f0e442/**
