name: manage-azure-policy-dd2eda95
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_Media_Services_accounts_should_disable_public_network_access_8bfe3603-0888-404a-87ff-5c1b6b4cc5e3/**'
#      - .github/workflows/manage-azure-policy-dd2eda95.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_dd2eda95}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_Media_Services_accounts_should_disable_public_network_access_8bfe3603-0888-404a-87ff-5c1b6b4cc5e3/**
