name: manage-azure-policy-b936c8a8
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Secrets_should_have_content_type_set_75262d3e-ba4a-4f43-85f8-9f72c090e5e3/**'
#      - .github/workflows/manage-azure-policy-b936c8a8.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_b936c8a8}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Secrets_should_have_content_type_set_75262d3e-ba4a-4f43-85f8-9f72c090e5e3/**
