name: manage-azure-policy-abd018d9
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/_Preview_Container_Registry_should_use_a_virtual_network_service_endpoint_c4857be7-912a-4c75-87e6-e30292bcdf78/**'
#      - .github/workflows/manage-azure-policy-abd018d9.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_abd018d9}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/_Preview_Container_Registry_should_use_a_virtual_network_service_endpoint_c4857be7-912a-4c75-87e6-e30292bcdf78/**
