name: manage-azure-policy-b17b7117
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Cosmos_DB_should_use_a_virtual_network_service_endpoint_e0a2b1a3-f7f9-4569-807f-2a9edebdf4d9/**'
#      - .github/workflows/manage-azure-policy-b17b7117.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_b17b7117}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Cosmos_DB_should_use_a_virtual_network_service_endpoint_e0a2b1a3-f7f9-4569-807f-2a9edebdf4d9/**
