name: manage-azure-policy-770da954
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Service_Bus_Namespaces_should_disable_public_network_access_cbd11fd3-3002-4907-b6c8-579f0e700e13/**'
#      - .github/workflows/manage-azure-policy-770da954.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_770da954}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Service_Bus_Namespaces_should_disable_public_network_access_cbd11fd3-3002-4907-b6c8-579f0e700e13/**
