name: manage-azure-policy-978da504
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Authorized_IP_ranges_should_be_defined_on_Kubernetes_Services_0e246bcf-5f6f-4f87-bc6f-775d4712c7ea/**'
#      - .github/workflows/manage-azure-policy-978da504.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_978da504}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Authorized_IP_ranges_should_be_defined_on_Kubernetes_Services_0e246bcf-5f6f-4f87-bc6f-775d4712c7ea/**
