name: manage-azure-policy-4b3472a0
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_Databricks_Workspaces_should_disable_public_network_access_0e7849de-b939-4c50-ab48-fc6b0f5eeba2/**'
#      - .github/workflows/manage-azure-policy-4b3472a0.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_4b3472a0}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_Databricks_Workspaces_should_disable_public_network_access_0e7849de-b939-4c50-ab48-fc6b0f5eeba2/**
