name: manage-azure-policy-b7692889
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/An_activity_log_alert_should_exist_for_specific_Administrative_operations_b954148f-4c11-4c38-8221-be76711e194a/**'
#      - .github/workflows/manage-azure-policy-b7692889.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_b7692889}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/An_activity_log_alert_should_exist_for_specific_Administrative_operations_b954148f-4c11-4c38-8221-be76711e194a/**
