name: manage-azure-policy-63870420
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/_Preview_All_Internet_traffic_should_be_routed_via_your_deployed_Azure_Firewall_fc5e4038-4584-4632-8c85-c0448d374b2c/**'
#      - .github/workflows/manage-azure-policy-63870420.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_63870420}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/_Preview_All_Internet_traffic_should_be_routed_via_your_deployed_Azure_Firewall_fc5e4038-4584-4632-8c85-c0448d374b2c/**
