name: manage-azure-policy-dd45f173
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_Event_Grid_domains_should_disable_public_network_access_f8f774be-6aee-492a-9e29-486ef81f3a68/**'
#      - .github/workflows/manage-azure-policy-dd45f173.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_dd45f173}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_Event_Grid_domains_should_disable_public_network_access_f8f774be-6aee-492a-9e29-486ef81f3a68/**
