name: manage-azure-policy-5408e900
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/MySQL_server_should_use_a_virtual_network_service_endpoint_3375856c-3824-4e0e-ae6a-79e011dd4c47/**'
#      - .github/workflows/manage-azure-policy-5408e900.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_5408e900}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/MySQL_server_should_use_a_virtual_network_service_endpoint_3375856c-3824-4e0e-ae6a-79e011dd4c47/**
