name: manage-azure-policy-2b4b9298
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_Cosmos_DB_accounts_should_have_firewall_rules_862e97cf-49fc-4a5c-9de4-40d4e2e7c8eb/**'
#      - .github/workflows/manage-azure-policy-2b4b9298.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_2b4b9298}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_Cosmos_DB_accounts_should_have_firewall_rules_862e97cf-49fc-4a5c-9de4-40d4e2e7c8eb/**
