name: manage-azure-policy-874af299
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/_Deprecated_App_Services_should_disable_public_network_access_63a0ac64-5d5f-4569-8a3d-df67cc1ce9d7/**'
#      - .github/workflows/manage-azure-policy-874af299.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_874af299}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/_Deprecated_App_Services_should_disable_public_network_access_63a0ac64-5d5f-4569-8a3d-df67cc1ce9d7/**
