name: manage-azure-policy-9f229fd5
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/An_activity_log_alert_should_exist_for_specific_Policy_operations_c5447c04-a4d7-4ba8-a263-c9ee321a6858/**'
#      - .github/workflows/manage-azure-policy-9f229fd5.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_9f229fd5}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/An_activity_log_alert_should_exist_for_specific_Policy_operations_c5447c04-a4d7-4ba8-a263-c9ee321a6858/**
